platform :ios do

  lane :lint do
    swiftlint(
      mode: :lint,
      path: "iosApp/iosApp",
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  private_lane :build_sync_sphere do |options|
    xcversion(version: "15.0.1")
    setup_ci
    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'iosApp/iosApp.xcodeproj',
      targets: 'iosApp',
      profile_name: 'match AppStore com.joetr.sync.sphere',
      profile_uuid: 'de173048-3d3d-4075-98f2-7e73f292bf86'
    )
    update_code_signing_settings(
      # Automatic signing seems to be a good thing to have on in dev but will not work in CI
      use_automatic_signing: false,
      # The default value for this is iOS Development which is not appropriate for release
      code_sign_identity: "Apple Distribution",
      path: 'iosApp/iosApp.xcodeproj'
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.sync.sphere',
      readonly: true
    )
    match(
      app_identifier: ["com.joetr.sync.sphere"],
      type: options[:type] || "appstore"
    )
    build_app(
      export_method: "app-store",
      workspace: "iosApp/iosApp.xcworkspace",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: false,
      skip_codesigning: false,
    )
  end

  lane :build do
    lint()
    build_sync_sphere(scheme: "iosApp")
  end

end


platform :ios do

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.sync.sphere',
      readonly: true
    )
  end
end