platform :ios do

  lane :lint do
    swiftlint(
      mode: :lint,
      path: "iosApp/iosApp",
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

  private_lane :build_sync_sphere do |options|
    xcversion(version: "15.0.1")
    build_app(
      workspace: "iosApp/iosApp.xcworkspace",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: false,
      skip_codesigning: false
    )
  end

  lane :build do
    lint()
    build_sync_sphere(scheme: "iosApp")
  end

end