platform :ios do

  lane :lint do
    swiftlint(
      mode: :lint,
      path: "iosApp/iosApp",
      strict: true,
      raise_if_swiftlint_error: true
    )
  end

    private_lane :build_sync_sphere do |options|
      xcversion(version: "15.0.1")
      build_app(
        export_method: "app-store",
        workspace: "iosApp/iosApp.xcworkspace",
        scheme: options[:scheme],
        buildlog_path: "build/fastlane-buildlog",
        skip_package_ipa: true,
        skip_codesigning: true,
      )
    end

  private_lane :release_sync_sphere do |options|
    setup_ci
    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'iosApp/iosApp.xcodeproj',
      targets: 'iosApp',
      profile_name: 'match AppStore com.joetr.sync.sphere',
      profile_uuid: 'de173048-3d3d-4075-98f2-7e73f292bf86'
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "Apple Distribution",
      path: 'iosApp/iosApp.xcodeproj'
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.sync.sphere',
      readonly: true
    )
    match(
      app_identifier: ["com.joetr.sync.sphere"],
      type: options[:type] || "appstore"
    )
    increment_build_number(
      xcodeproj: "iosApp/iosApp.xcodeproj",
      build_number: ENV['SYNC_SPHERE_BUILD_NUMBER']
    )
    build_app(
      export_method: "app-store",
      workspace: "iosApp/iosApp.xcworkspace",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: false,
      skip_codesigning: false,
    )
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
      is_key_content_base64: true,
      duration: 1200,
    )

    upload_to_testflight(
        app_identifier: "com.joetr.sync.sphere",
        skip_waiting_for_build_processing: true
    )
  end

  lane :build do
    lint()
    build_sync_sphere(scheme: "iosApp")
  end

  lane :release do
    lint()
    release_sync_sphere(scheme: "iosApp")
  end

end


platform :ios do

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.joetr.sync.sphere',
      readonly: true
    )
  end
end