name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  code-style:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Check convention plugins code style with Spotless
        run: ./gradlew -p gradle/build-logic spotlessCheck

      - name: Check code style with Spotless
        run: ./gradlew spotlessCheck

      - name: Check code style with Detekt
        run: ./gradlew detektAll

  android:
    needs: [code-style]
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build Android App
        run: |
          ./gradlew \
            :androidApp:bundle \
            :androidApp:build

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-build-outputs
          path: android-app/release/

  ios:
    needs: [code-style]
    runs-on: macos-latest
    timeout-minutes: 60
    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build iOS application
        run: bundle exec fastlane ios build

      - name: Upload build outputs
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: ios-build-outputs
          path: |
            *.ipa
            *.dSYM.zip

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ios-logs
          path: |
            **/fastlane-buildlog